# Webscrapping
Comparando precios de frutas y verduras en las tiendas

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

## Plaza Vea

In [9]:
url = "https://www.plazavea.com.pe/frutas-y-verduras"
r = requests.get(url)

soup = BeautifulSoup(r.text, 'html')

names = []
for name in soup.find_all('a', attrs={"class":"Showcase__name"}):
    names.append(name.text)

# Los precios se repiten 3 veces porque la etiqueta div class="Showcase_salePrice"
# se repite como código y en forma de comentarios adicionales. Asi que se guardan
# todas las ocurrencias para luego barrer la lista en saltos de tres elementos
prices = []    
for price in soup.find_all('div', attrs={"class":"Showcase__salePrice"}):
    prices.append(price.text)
    
# Se barren todos los elementos de names y los de prices en saltos de tres
data = [[name, price] for name, price in zip(names, prices[::3])]    
    
plazavea_df = pd.DataFrame(data, columns=['Producto', 'Precio'])
plazavea_df

                               Producto   Precio
0                          Palta Fuerte  S/ 8.99
1                       Tomate Italiano  S/ 2.49
2                     Naranja para Jugo  S/ 1.69
3                           Limón Ácido  S/ 2.49
4           Plátano de Seda Paquete 5un  S/ 2.89
5                Limón Ácido Malla 500g  S/ 1.70
6            Zanahoria Entera Malla 1Kg  S/ 2.90
7          Papa Yungay BELL'S Malla 2Kg  S/ 3.20
8         Cebolla Roja BELL'S Bolsa 2Kg  S/ 3.60
9                    Uva Verde sin Pepa  S/ 8.99
10                        Zapallo Macre  S/ 3.49
11                          Piña Golden  S/ 5.89
12                               Sandía  S/ 1.29
13                               Papaya  S/ 4.79
14                         Cebolla Roja  S/ 1.99
15  Lechuga Americana BELL's Bolsa 300g  S/ 2.29
16                      Choclo x unidad  S/ 1.99
17            Camote Amarillo Procesado  S/ 2.60
18         Manzana Royal Gala Importada  S/ 6.89
19           Espinaca BELL'S Bolsa 350g  S/ 2.90
20                       Manzana Israel  S/ 2.49
21                        Melón Coquito  S/ 2.29
22                            Pepinillo  S/ 2.50
23                            Zanahoria  S/ 2.99

## Wong

In [3]:
url = "https://www.wong.pe/frutas-y-verduras"
r = requests.get(url)

soup = BeautifulSoup(r.text, 'lxml')

data = []
for name, price in zip(soup.find_all('a', class_="product-item__name"), 
                       soup.find_all('span', class_="product-prices__value product-prices__value--best-price")):
    data.append([name.text, price.text])
    
wong_df = pd.DataFrame(data, columns=['Producto', 'Precio'])
wong_df

                                             Producto    Precio
0                                Tomate Italiano x kg  S/. 2.99
1                                          Limón x kg  S/. 3.09
2                                         Papaya x kg  S/. 4.79
3                               Choclo Serrano x unid  S/. 2.29
4                 Papa Amarilla Tumbay Procesada x kg  S/. 6.39
5                                      Zanahoria x kg  S/. 4.49
6                                       Pimiento x kg  S/. 5.39
7                                        Brócoli x kg  S/. 5.49
8               Plátano de Seda Tipo Exportación x kg  S/. 4.99
9                            Piña Golden Premium x kg  S/. 5.89
10                            Palta Fuerte Verde x kg  S/. 9.99
11                             Mango Edward Wong x kg  S/. 8.99
12   Cebolla Roja Seleccionada Campo Lindo Malla 1 Kg  S/. 4.90
13    Naranja para Jugo La Pecosita Wong Bolsa 2.5 Kg  S/. 9.49
14                     Camote Amarillo Procesado x kg  S/. 2.89
15  Espárrago Verde Tipo Exportación Wong atado 32...  S/. 6.99
16                    Cebolla Blanca Campo Lindo x kg  S/. 4.99
17                                 Apio Verde x atado  S/. 3.39

## Metro

In [4]:
url = "https://www.metro.pe/frutas-y-verduras"
r = requests.get(url)

soup = BeautifulSoup(r.text, 'lxml')

data = []
for name, price in zip(soup.find_all('a', class_="product-item__name"), 
                       soup.find_all('span', class_="product-prices__value product-prices__value--best-price")):
    data.append([name.text, price.text])
    
metro_df = pd.DataFrame(data, columns=['Producto', 'Precio'])
metro_df

                                     Producto    Precio
0                           Papaya Metro x kg  S/. 3.99
1   Tomate Italiano Siembra Dorada Metro x kg  S/. 3.49
2                  Plátano de Seda Metro x kg  S/. 2.79
3    Naranja para Jugo Chanchamayo Metro x kg  S/. 1.49
4                     Palta Fuerte Metro x kg  S/. 8.99
5                                  Limón x kg  S/. 2.49
6                           Sandía Metro x kg  S/. 1.19
7                          Brócoli Metro x kg  S/. 4.99
8                            Papa Blanca x kg  S/. 0.99
9        Papa Canchán Procesada Especial x kg  S/. 1.49
10              Camote Amarillo Especial x kg  S/. 2.49
11                          Apio Metro x unid  S/. 2.79
12                   Melón Coquito Metro x kg  S/. 2.49
13              Mandarina sin Pepa Metro x kg  S/. 4.49
14                     Choclo Especial x unid  S/. 1.99
15            Manzana Israel Añawi Metro x kg  S/. 1.99
16                    Mango Edward Metro x kg  S/. 5.49
17                    Zanahoria Especial x kg  S/. 2.79

## Comparación de precios por productos

In [5]:
plazavea_df[plazavea_df['Producto'].str.contains('papa', case=False)]    # case=False: No considera las may/min

                        Producto   Precio
7   Papa Yungay BELL'S Malla 2Kg  S/ 3.20
13                        Papaya  S/ 4.79

In [6]:
wong_df[wong_df['Producto'].str.contains('papa', case=False)]

                              Producto    Precio
2                          Papaya x kg  S/. 4.79
4  Papa Amarilla Tumbay Procesada x kg  S/. 6.39

In [7]:
metro_df[metro_df['Producto'].str.contains('papa', case=False)]

                               Producto    Precio
0                     Papaya Metro x kg  S/. 3.99
8                      Papa Blanca x kg  S/. 0.99
9  Papa Canchán Procesada Especial x kg  S/. 1.49